---
- hosts: localhost
  roles:
    - role: dotfiles
      tags: ['dotfiles']
    - role: shell
      tags: ['shell']
    - role: homebrew
      tags: ['homebrew']
      when: "ansible_distribution == 'MacOSX'"
    - role: npm
      tags: ['npm']
    - role: vim
      tags: ['vim']
