---
- name: download Homebrew install script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest=vendor/homebrew/install

- name: install Homebrew
  command: ruby vendor/homebrew/install creates=/usr/local/bin/brew

- name: update Homebrew
  homebrew: update_homebrew=yes

- name: taps
  homebrew_tap: "tap={{ item }}"
  with_items: taps

- name: brews
  homebrew: "name={{ item }}"
  with_items: brews

- name: casks
  homebrew_cask: "name={{ item }}"
  with_items: casks

- name: homebrew | clean up old versions
  command: brew cleanup

- name: homebrew | clean up old casks
  command: brew cask cleanup
