- name: Install Vundle
  git: repo=https://github.com/gmarik/vundle.git
       dest=~/.vim/bundle/vundle
       update=no
       depth=1
  register: vundle_installed

- name: Initialize Vundle
  command: vim -s roles/vim/files/install_bundles
  when: vundle_installed.changed

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_env.PWD}}/roles/vim/vars/{{ ansible_distribution }}.yml"
    - "{{ ansible_env.PWD}}/roles/vim/vars/default.yml"

- name: configure Command-T
  command:
    ruby extconf.rb
    chdir={{ command_t_base }}/ruby/command-t

- name: compile Command-T
  command:
    make
    chdir={{ command_t_base }}/ruby/command-t

- stat: path={{you_complete_me_base}}
  register: ycm

- name: install YouCompleteMe
  command: ./install.sh chdir={{ you_complete_me_base }}
  when: ycm.stat.exists == True
